MESSAGE(STATUS "Importing VTK...")
FIND_PACKAGE(VTK)
IF(VTK_FOUND)
  OPTION(InSAR_USE_VTK "Use VTK library." ON)
ELSE(VTK_FOUND)
  OPTION(InSAR_USE_VTK "Use VTK library." OFF)
ENDIF(VTK_FOUND)

INCLUDE(${VTK_USE_FILE})